apiVersion: apps/v1
kind: Deployment
metadata:
  name: listar-git-deployment
  labels:
    app: listar-git-app
spec:
  selector:
    matchLabels:
      app: listar-git-app
      tier: service
  template:
    metadata:
      labels:
        app: listar-git-app
        tier: service
    spec:
      containers:
      - name: listar-git-app
        git: registry.hub.docker.com/donalbert/listar-git:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: listar-git-service
  labels:
    app: listar-git-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: listar-git-app